### ISSUE TITLE
tfenv: tfenv-use: [ERROR] 'terraform --version' failed. Something is seriously wrong

### ISSUE THREAD

**Issue by lauraaraviciute** [tfutils/tfenv#116] opened 2019-06-28 15:19 UTC
Hi

I'm trying to install tfenv on a docker image and the following occurs when building the image:

```
========starting package install script==========
intalling tfenv
[INFO] Installing Terraform v0.11.10
[INFO] Downloading release tarball from https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
######################################################################## 100.0%
[INFO] Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_SHA256SUMS
tfenv: tfenv-install: [WARN] No keybase install found, skipping OpenPGP signature verification
tfenv: tfenv-install: [WARN] No shasum tool available. Skipping SHA256 hash validation
Archive:  tfenv_download.GV1oy7/terraform_0.11.10_linux_amd64.zip
  inflating: /builder_home/tfenv/versions/0.11.10/terraform
[INFO] Installation of terraform v0.11.10 successful
[INFO] Switching to v0.11.10
/usr/local/bin/terraform: line 6: which: command not found
/usr/local/bin/terraform: line 6: /tfenv: No such file or directory
tfenv: tfenv-use: [ERROR] 'terraform --version' failed. Something is seriously wrong
The command '/bin/sh -c chmod +x /scripts/install_tfenv.sh      && /scripts/install_tfenv.sh' returned a non-zero code: 1
```

I seen an open PR for making the install location configurable, is that going to happen anytime soon? Are there any workarounds to the error I'm receiving? 

More context or information would be greatly appreciated.

**Comment by iamhsa** [comment] 2019-07-04 10:05
@lauraaraviciute 
I use tfenv in docker without any problems.

In our case, one dependency is missing (which) in your docker image.
`/usr/local/bin/terraform: line 6: which: command not found`

Could you try to install it ?

I think this dependence should be removed.
I look to propose something in a PR.

**Comment by iamhsa** [comment] 2019-07-05 08:00
I have proposed a PR to remove 'which' dependency.
See #119

**Comment by lauraaraviciute** [comment] 2019-07-05 08:52
Thanks for creating that PR @iamhsa . 

So tfenv installs properly now, but symlinks don't seem to work - what are the proper installation steps you use in that case? I might be doing something wrong when setting up symlinks as I am still only able to use tfenv from the folder in which it was installed - and as we are trying to install this on our jenkins image I would like to be able to execute tfenv from any directory. 

I'm using the following instructions:
```
ln -s ~/.tfenv/bin/* /usr/local/bin
```

**Comment by iamhsa** [comment] 2019-07-05 15:30
@lauraaraviciute : 
In my case I always use tfenv in /home/user so I don't have this problems.

In your case I think, you can, clone tfenv in /opt/tfenv  (as /opt is generally 755) and make symlink in /usr/local/bin.

Here is a sample dockerfile that seems to work as you want (be carefull it's based on Archlinux image).

```Dockerfile
# Select archlinux as based image
FROM archlinux/base

# Work in /root
WORKDIR /root

# Update distrib packages and install tfenv dependencies
RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm git unzip which awk

# Install tfenv and configure env.
RUN git clone https://github.com/tfutils/tfenv.git /opt/tfenv \
  && ln -s /opt/tfenv/bin/* /usr/local/bin/
```
I hope I have answered the question.

**Comment by Zordrak** [comment] 2019-07-09 07:56
> I seen an open PR for making the install location configurable, is that going to happen anytime soon? 

Additional features aren't getting a lot of attention at the mo. I hope to have time to consider them in the future. In the meantime I welcome PRs we can review for inclustion. This one is certainly quite high on the priority list for features.

**Comment by Zordrak** [comment] 2019-07-09 08:00
#119 has been merged to remove the `which` dependency. Are there any other unaddressed problems in this issue? Is `tfenv --version` working as expected for each of your environments?

**Comment by Zordrak** [comment] 2019-07-09 13:50
I've tried to reproduce this and I think there may be a case here of bad error messages. I noted that the only time I got a failure which was indeed the same "terraform --version failed" error, it was because tfenv had been executed without $TFENV_HOME/bin being added to the $PATH

**Comment by Zordrak** [comment] 2020-04-20 16:13
Please re-open if issues remain in v2.0.0

**Closed by Zordrak** 2020-04-20 16:13 UTC
Labels: moreinfo

**Comment by Roxyrob** [comment] 2020-06-30 14:16
Found similar error in tfenv use command:

```
tfenv use 0.13.0-beta2

```
returns

```
Switching default version to v0.13.0-beta2
Error parsing command-line flags: flag provided but not defined: -version

'terraform --version' failed. Something is seriously wrong

```
Nothing bad as the new terraform version is pointed anyway by tfenv, but probably you can avoid this using "terraform version" instead of removed "--version" option to prepare to new terraform 0.13 release
